### ISSUE TITLE
Uncaught TypeError: editor.displayBuffer.screenPositionForPixelPosition is not a function

### ISSUE THREAD

**Issue by steelbrain** [tmunro/remember-file-positions#2]
Steps to reproduction:
1. Download the latest atom beta
2. Try to find something

**Atom Version**: 1.1.0-beta1
**System**: Ubuntu 15.04
**Thrown From**: [remember-file-positions](https://github.com/tmunro/remember-file-positions) package, v0.1.6
### Stack Trace

Uncaught TypeError: editor.displayBuffer.screenPositionForPixelPosition is not a function

```
At /home/steel/.atom/packages/remember-file-positions/lib/remember-file-positions.coffee:45

TypeError: editor.displayBuffer.screenPositionForPixelPosition is not a function
  at Object.module.exports.RememberFilePositions.handleChangeScroll (/home/steel/.atom/packages/remember-file-positions/lib/remember-file-positions.coffee:45:43)
  at /home/steel/.atom/packages/remember-file-positions/lib/remember-file-positions.coffee:16:10
  at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom-beta/resources/app.asar/src/text-editor-element.js:105:47
  at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (/usr/share/atom-beta/resources/app.asar/src/text-editor-presenter.js:1026:29)
  at TextEditorPresenter.module.exports.TextEditorPresenter.commitPendingScrollTopPosition (/usr/share/atom-beta/resources/app.asar/src/text-editor-presenter.js:2054:14)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/usr/share/atom-beta/resources/app.asar/src/text-editor-presenter.js:108:12)
  at LinesYardstick.module.exports.LinesYardstick.prepareScreenRowsForMeasurement (/usr/share/atom-beta/resources/app.asar/src/lines-yardstick.js:24:63)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/usr/share/atom-beta/resources/app.asar/src/text-editor-presenter.js:181:27)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom-beta/resources/app.asar/src/text-editor-component.js:196:38)
  at /usr/share/atom-beta/resources/app.asar/src/text-editor-component.js:298:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom-beta/resources/app.asar/src/view-registry.js:174:9)
  at /usr/share/atom-beta/resources/app.asar/src/view-registry.js:3:61

```
### Commands

```
     -2:30.9.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:30.6.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -2:29.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:29.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:28.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:28.6.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -2:28.1.0 pane:show-previous-item (div.settings-view.pane-item)
     -0:53.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:52.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:52.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:51.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:18.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  5x -0:17.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:16.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:01.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": true,
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

**Comment by tmunro** [comment]
Thanks for opening this - the coordinates system has changed completely in the beta, and I've been meaning to update to take care of it. Unfortunately, I think this is a change that will destroy any previously saved positions.
