### ISSUE TITLE
Failed to activate the remember-file-positions package on Atom 1.1.0

### ISSUE THREAD

**Issue by paambaati** [tmunro/remember-file-positions#3]
Steps to reproduce —
1. Upgrade Atom from 1.0.19 to 1.1.0.
2. Error!

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: [remember-file-positions](https://github.com/tmunro/remember-file-positions) package, v0.2.0
### Stack Trace

Failed to activate the remember-file-positions package

```
At editor.displayBuffer.pixelPositionForScreenPosition is not a function

TypeError: editor.displayBuffer.pixelPositionForScreenPosition is not a function
    at Object.module.exports.RememberFilePositions.setCursorAndScroll (/Users/gp/.atom/packages/remember-file-positions/lib/remember-file-positions.coffee:39:48)
    at Object.module.exports.RememberFilePositions.handleAddTextEditor (/Users/gp/.atom/packages/remember-file-positions/lib/remember-file-positions.coffee:27:8)
    at /Users/gp/.atom/packages/remember-file-positions/lib/remember-file-positions.coffee:14:8
    at Workspace.module.exports.Workspace.observeTextEditors (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/workspace.js:267:9)
    at Object.module.exports.RememberFilePositions.activate (/Users/gp/.atom/packages/remember-file-positions/lib/remember-file-positions.coffee:13:39)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
```
### Commands

```
     -0:20.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-material-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "archive-view",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "metrics",
      "wrap-guide"
    ],
    "ignoredNames": [
      ".git",
      ".vscode",
      ".DS_Store",
      "node_modules",
      ".imdone"
    ],
    "projectHome": "/Users/gp/Projects"
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v0.6.3
autoclose-html, v0.19.0
docblockr, v0.7.3
file-type-icons, v0.7.3
highlight-selected, v0.10.1
linter, v1.9.1
linter-eslint, v3.2.0
minimap, v4.15.0
minimap-highlight-selected, v4.3.1
remember-file-positions, v0.2.0

# Dev
No dev packages
```

**Comment by tmunro** [comment]
Ah, darn. I tried to future proof the package when I found out about the API changes in 1.1.0, but I must have missed something.

**Comment by tmunro** [comment]
Hmm, I don't get this error when Atom 1.1.0 is activated and 0.2.0 is installed. I build Atom from source, so I may get different results. Does this happen after you restart Atom with 0.2.0 installed?

**Comment by paambaati** [comment]
Oh wait. It happened only the first time I restarted Atom after updating to 1.1.0. After that, I restarted it again and now I don't see the issue anymore.

**Comment by tmunro** [comment]
I'm pretty sure this is caused by 0.1.6 not excluding support for 1.1, so it doesn't disable itself and force an update.
